export const sampleRooms = {
    "rooms": [
      {
        "name": "Wall",
        "id": 0,
        "description": "A wholly unremarkable wall",
        "x": 0,
        "y": 0,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 1,
        "description": "A wholly unremarkable wall",
        "x": 1,
        "y": 0,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 2,
        "description": "A wholly unremarkable wall",
        "x": 2,
        "y": 0,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 3,
        "description": "A wholly unremarkable wall",
        "x": 3,
        "y": 0,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 4,
        "description": "A wholly unremarkable wall",
        "x": 4,
        "y": 0,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 5,
        "description": "A wholly unremarkable wall",
        "x": 5,
        "y": 0,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 6,
        "description": "A wholly unremarkable wall",
        "x": 6,
        "y": 0,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 7,
        "description": "A wholly unremarkable wall",
        "x": 7,
        "y": 0,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 8,
        "description": "A wholly unremarkable wall",
        "x": 8,
        "y": 0,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 9,
        "description": "A wholly unremarkable wall",
        "x": 9,
        "y": 0,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 10,
        "description": "A wholly unremarkable wall",
        "x": 10,
        "y": 0,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 11,
        "description": "A wholly unremarkable wall",
        "x": 0,
        "y": 1,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 12,
        "description": "Another empty room",
        "x": 1,
        "y": 1,
        "n": -1,
        "s": 23,
        "e": 13,
        "w": -1
      },
      {
        "name": "Room",
        "id": 13,
        "description": "Another empty room",
        "x": 2,
        "y": 1,
        "n": -1,
        "s": -1,
        "e": 14,
        "w": 12
      },
      {
        "name": "Room",
        "id": 14,
        "description": "Another empty room",
        "x": 3,
        "y": 1,
        "n": -1,
        "s": 25,
        "e": 15,
        "w": 13
      },
      {
        "name": "Room",
        "id": 15,
        "description": "Another empty room",
        "x": 4,
        "y": 1,
        "n": -1,
        "s": 26,
        "e": 16,
        "w": 14
      },
      {
        "name": "Room",
        "id": 16,
        "description": "Another empty room",
        "x": 5,
        "y": 1,
        "n": -1,
        "s": 27,
        "e": -1,
        "w": 15
      },
      {
        "name": "Wall",
        "id": 17,
        "description": "A wholly unremarkable wall",
        "x": 6,
        "y": 1,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 18,
        "description": "Another empty room",
        "x": 7,
        "y": 1,
        "n": -1,
        "s": 29,
        "e": 19,
        "w": -1
      },
      {
        "name": "Room",
        "id": 19,
        "description": "Another empty room",
        "x": 8,
        "y": 1,
        "n": -1,
        "s": -1,
        "e": 20,
        "w": 18
      },
      {
        "name": "Room",
        "id": 20,
        "description": "Another empty room",
        "x": 9,
        "y": 1,
        "n": -1,
        "s": 31,
        "e": -1,
        "w": 19
      },
      {
        "name": "Wall",
        "id": 21,
        "description": "A wholly unremarkable wall",
        "x": 10,
        "y": 1,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 22,
        "description": "A wholly unremarkable wall",
        "x": 0,
        "y": 2,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 23,
        "description": "Another empty room",
        "x": 1,
        "y": 2,
        "n": 12,
        "s": 34,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 24,
        "description": "A wholly unremarkable wall",
        "x": 2,
        "y": 2,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 25,
        "description": "Another empty room",
        "x": 3,
        "y": 2,
        "n": 14,
        "s": 36,
        "e": 26,
        "w": -1
      },
      {
        "name": "Room",
        "id": 26,
        "description": "Another empty room",
        "x": 4,
        "y": 2,
        "n": 15,
        "s": 37,
        "e": 27,
        "w": 25
      },
      {
        "name": "Room",
        "id": 27,
        "description": "Another empty room",
        "x": 5,
        "y": 2,
        "n": 16,
        "s": 38,
        "e": -1,
        "w": 26
      },
      {
        "name": "Wall",
        "id": 28,
        "description": "A wholly unremarkable wall",
        "x": 6,
        "y": 2,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 29,
        "description": "Another empty room",
        "x": 7,
        "y": 2,
        "n": 18,
        "s": 40,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 30,
        "description": "A wholly unremarkable wall",
        "x": 8,
        "y": 2,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 31,
        "description": "Another empty room",
        "x": 9,
        "y": 2,
        "n": 20,
        "s": 42,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 32,
        "description": "A wholly unremarkable wall",
        "x": 10,
        "y": 2,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 33,
        "description": "A wholly unremarkable wall",
        "x": 0,
        "y": 3,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 34,
        "description": "Another empty room",
        "x": 1,
        "y": 3,
        "n": 23,
        "s": 45,
        "e": 35,
        "w": -1
      },
      {
        "name": "Room",
        "id": 35,
        "description": "Another empty room",
        "x": 2,
        "y": 3,
        "n": -1,
        "s": -1,
        "e": 36,
        "w": 34
      },
      {
        "name": "Room",
        "id": 36,
        "description": "Another empty room",
        "x": 3,
        "y": 3,
        "n": 25,
        "s": -1,
        "e": 37,
        "w": 35
      },
      {
        "name": "Room",
        "id": 37,
        "description": "Another empty room",
        "x": 4,
        "y": 3,
        "n": 26,
        "s": -1,
        "e": 38,
        "w": 36
      },
      {
        "name": "Room",
        "id": 38,
        "description": "Another empty room",
        "x": 5,
        "y": 3,
        "n": 27,
        "s": 49,
        "e": -1,
        "w": 37
      },
      {
        "name": "Wall",
        "id": 39,
        "description": "A wholly unremarkable wall",
        "x": 6,
        "y": 3,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 40,
        "description": "Another empty room",
        "x": 7,
        "y": 3,
        "n": 29,
        "s": 51,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 41,
        "description": "A wholly unremarkable wall",
        "x": 8,
        "y": 3,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 42,
        "description": "Another empty room",
        "x": 9,
        "y": 3,
        "n": 31,
        "s": 53,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 43,
        "description": "A wholly unremarkable wall",
        "x": 10,
        "y": 3,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 44,
        "description": "A wholly unremarkable wall",
        "x": 0,
        "y": 4,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 45,
        "description": "Another empty room",
        "x": 1,
        "y": 4,
        "n": 34,
        "s": 56,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 46,
        "description": "A wholly unremarkable wall",
        "x": 2,
        "y": 4,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 47,
        "description": "A wholly unremarkable wall",
        "x": 3,
        "y": 4,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 48,
        "description": "A wholly unremarkable wall",
        "x": 4,
        "y": 4,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 49,
        "description": "Another empty room",
        "x": 5,
        "y": 4,
        "n": 38,
        "s": 60,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 50,
        "description": "A wholly unremarkable wall",
        "x": 6,
        "y": 4,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 51,
        "description": "Another empty room",
        "x": 7,
        "y": 4,
        "n": 40,
        "s": 62,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 52,
        "description": "A wholly unremarkable wall",
        "x": 8,
        "y": 4,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 53,
        "description": "Another empty room",
        "x": 9,
        "y": 4,
        "n": 42,
        "s": 64,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 54,
        "description": "A wholly unremarkable wall",
        "x": 10,
        "y": 4,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 55,
        "description": "A wholly unremarkable wall",
        "x": 0,
        "y": 5,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 56,
        "description": "Another empty room",
        "x": 1,
        "y": 5,
        "n": 45,
        "s": 67,
        "e": 57,
        "w": -1
      },
      {
        "name": "Room",
        "id": 57,
        "description": "Another empty room",
        "x": 2,
        "y": 5,
        "n": -1,
        "s": -1,
        "e": 58,
        "w": 56
      },
      {
        "name": "Room",
        "id": 58,
        "description": "Another empty room",
        "x": 3,
        "y": 5,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": 57
      },
      {
        "name": "Wall",
        "id": 59,
        "description": "A wholly unremarkable wall",
        "x": 4,
        "y": 5,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 60,
        "description": "Another empty room",
        "x": 5,
        "y": 5,
        "n": 49,
        "s": -1,
        "e": 61,
        "w": -1
      },
      {
        "name": "Room",
        "id": 61,
        "description": "Another empty room",
        "x": 6,
        "y": 5,
        "n": -1,
        "s": -1,
        "e": 62,
        "w": 60
      },
      {
        "name": "Room",
        "id": 62,
        "description": "Another empty room",
        "x": 7,
        "y": 5,
        "n": 51,
        "s": -1,
        "e": -1,
        "w": 61
      },
      {
        "name": "Wall",
        "id": 63,
        "description": "A wholly unremarkable wall",
        "x": 8,
        "y": 5,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 64,
        "description": "Another empty room",
        "x": 9,
        "y": 5,
        "n": 53,
        "s": 75,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 65,
        "description": "A wholly unremarkable wall",
        "x": 10,
        "y": 5,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 66,
        "description": "A wholly unremarkable wall",
        "x": 0,
        "y": 6,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 67,
        "description": "Another empty room",
        "x": 1,
        "y": 6,
        "n": 56,
        "s": 78,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 68,
        "description": "A wholly unremarkable wall",
        "x": 2,
        "y": 6,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 69,
        "description": "A wholly unremarkable wall",
        "x": 3,
        "y": 6,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 70,
        "description": "A wholly unremarkable wall",
        "x": 4,
        "y": 6,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 71,
        "description": "A wholly unremarkable wall",
        "x": 5,
        "y": 6,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 72,
        "description": "A wholly unremarkable wall",
        "x": 6,
        "y": 6,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 73,
        "description": "A wholly unremarkable wall",
        "x": 7,
        "y": 6,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 74,
        "description": "A wholly unremarkable wall",
        "x": 8,
        "y": 6,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 75,
        "description": "Another empty room",
        "x": 9,
        "y": 6,
        "n": 64,
        "s": 86,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 76,
        "description": "A wholly unremarkable wall",
        "x": 10,
        "y": 6,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 77,
        "description": "A wholly unremarkable wall",
        "x": 0,
        "y": 7,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 78,
        "description": "Another empty room",
        "x": 1,
        "y": 7,
        "n": 67,
        "s": 89,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 79,
        "description": "A wholly unremarkable wall",
        "x": 2,
        "y": 7,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 80,
        "description": "Another empty room",
        "x": 3,
        "y": 7,
        "n": -1,
        "s": 91,
        "e": 81,
        "w": -1
      },
      {
        "name": "Room",
        "id": 81,
        "description": "Another empty room",
        "x": 4,
        "y": 7,
        "n": -1,
        "s": -1,
        "e": 82,
        "w": 80
      },
      {
        "name": "Room",
        "id": 82,
        "description": "Another empty room",
        "x": 5,
        "y": 7,
        "n": -1,
        "s": -1,
        "e": 83,
        "w": 81
      },
      {
        "name": "Room",
        "id": 83,
        "description": "Another empty room",
        "x": 6,
        "y": 7,
        "n": -1,
        "s": -1,
        "e": 84,
        "w": 82
      },
      {
        "name": "Room",
        "id": 84,
        "description": "Another empty room",
        "x": 7,
        "y": 7,
        "n": -1,
        "s": -1,
        "e": 85,
        "w": 83
      },
      {
        "name": "Room",
        "id": 85,
        "description": "Another empty room",
        "x": 8,
        "y": 7,
        "n": -1,
        "s": -1,
        "e": 86,
        "w": 84
      },
      {
        "name": "Room",
        "id": 86,
        "description": "Another empty room",
        "x": 9,
        "y": 7,
        "n": 75,
        "s": 97,
        "e": -1,
        "w": 85
      },
      {
        "name": "Wall",
        "id": 87,
        "description": "A wholly unremarkable wall",
        "x": 10,
        "y": 7,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 88,
        "description": "A wholly unremarkable wall",
        "x": 0,
        "y": 8,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 89,
        "description": "Another empty room",
        "x": 1,
        "y": 8,
        "n": 78,
        "s": 100,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 90,
        "description": "A wholly unremarkable wall",
        "x": 2,
        "y": 8,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 91,
        "description": "Another empty room",
        "x": 3,
        "y": 8,
        "n": 80,
        "s": 102,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 92,
        "description": "A wholly unremarkable wall",
        "x": 4,
        "y": 8,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 93,
        "description": "A wholly unremarkable wall",
        "x": 5,
        "y": 8,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 94,
        "description": "A wholly unremarkable wall",
        "x": 6,
        "y": 8,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 95,
        "description": "A wholly unremarkable wall",
        "x": 7,
        "y": 8,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 96,
        "description": "A wholly unremarkable wall",
        "x": 8,
        "y": 8,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 97,
        "description": "Another empty room",
        "x": 9,
        "y": 8,
        "n": 86,
        "s": 108,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 98,
        "description": "A wholly unremarkable wall",
        "x": 10,
        "y": 8,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 99,
        "description": "A wholly unremarkable wall",
        "x": 0,
        "y": 9,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 100,
        "description": "Another empty room",
        "x": 1,
        "y": 9,
        "n": 89,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 101,
        "description": "A wholly unremarkable wall",
        "x": 2,
        "y": 9,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 102,
        "description": "Another empty room",
        "x": 3,
        "y": 9,
        "n": 91,
        "s": -1,
        "e": 103,
        "w": -1
      },
      {
        "name": "Room",
        "id": 103,
        "description": "Another empty room",
        "x": 4,
        "y": 9,
        "n": -1,
        "s": -1,
        "e": 104,
        "w": 102
      },
      {
        "name": "Room",
        "id": 104,
        "description": "Another empty room",
        "x": 5,
        "y": 9,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": 103
      },
      {
        "name": "Wall",
        "id": 105,
        "description": "A wholly unremarkable wall",
        "x": 6,
        "y": 9,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Room",
        "id": 106,
        "description": "Another empty room",
        "x": 7,
        "y": 9,
        "n": -1,
        "s": -1,
        "e": 107,
        "w": -1
      },
      {
        "name": "Room",
        "id": 107,
        "description": "Another empty room",
        "x": 8,
        "y": 9,
        "n": -1,
        "s": -1,
        "e": 108,
        "w": 106
      },
      {
        "name": "Room",
        "id": 108,
        "description": "Another empty room",
        "x": 9,
        "y": 9,
        "n": 97,
        "s": -1,
        "e": -1,
        "w": 107
      },
      {
        "name": "Wall",
        "id": 109,
        "description": "A wholly unremarkable wall",
        "x": 10,
        "y": 9,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 110,
        "description": "A wholly unremarkable wall",
        "x": 0,
        "y": 10,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 111,
        "description": "A wholly unremarkable wall",
        "x": 1,
        "y": 10,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 112,
        "description": "A wholly unremarkable wall",
        "x": 2,
        "y": 10,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 113,
        "description": "A wholly unremarkable wall",
        "x": 3,
        "y": 10,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 114,
        "description": "A wholly unremarkable wall",
        "x": 4,
        "y": 10,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 115,
        "description": "A wholly unremarkable wall",
        "x": 5,
        "y": 10,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 116,
        "description": "A wholly unremarkable wall",
        "x": 6,
        "y": 10,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 117,
        "description": "A wholly unremarkable wall",
        "x": 7,
        "y": 10,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 118,
        "description": "A wholly unremarkable wall",
        "x": 8,
        "y": 10,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 119,
        "description": "A wholly unremarkable wall",
        "x": 9,
        "y": 10,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      },
      {
        "name": "Wall",
        "id": 120,
        "description": "A wholly unremarkable wall",
        "x": 10,
        "y": 10,
        "n": -1,
        "s": -1,
        "e": -1,
        "w": -1
      }
    ]
  }